-- 장바구니 테이블 생성
CREATE TABLE CART_ITEM (
    CART_ITEM_ID VARCHAR2(36) PRIMARY KEY,
    MEMBER_ID NUMBER NOT NULL,
    ITEM_TYPE VARCHAR2(10) NOT NULL, -- 'HOUSE' 또는 'CAR'
    ITEM_ID NUMBER NOT NULL,
    START_DATE DATE NOT NULL,
    END_DATE DATE NOT NULL,
    QUANTITY NUMBER DEFAULT 1,
    UNIT_PRICE NUMBER NOT NULL,
    TOTAL_PRICE NUMBER NOT NULL,
    ITEM_NAME VARCHAR2(200),
    ITEM_IMAGE VARCHAR2(500),
    ITEM_TYPE_NAME VARCHAR2(100),
    PICKUP_LOCATION VARCHAR2(100),
    RETURN_LOCATION VARCHAR2(100),
    ROOM_TYPE VARCHAR2(100),
    CREATED_AT DATE DEFAULT SYSDATE,
    UPDATED_AT DATE DEFAULT SYSDATE
);

-- 인덱스 생성
CREATE INDEX IDX_CART_MEMBER_ID ON CART_ITEM(MEMBER_ID);
CREATE INDEX IDX_CART_ITEM_TYPE ON CART_ITEM(ITEM_TYPE);
CREATE INDEX IDX_CART_CREATED_AT ON CART_ITEM(CREATED_AT);

-- 외래키 제약조건 (선택사항)
-- ALTER TABLE CART_ITEM ADD CONSTRAINT FK_CART_MEMBER 
--     FOREIGN KEY (MEMBER_ID) REFERENCES MEMBER(MEMBER_ID);

-- 테이블 코멘트
COMMENT ON TABLE CART_ITEM IS '장바구니 아이템 테이블';
COMMENT ON COLUMN CART_ITEM.CART_ITEM_ID IS '장바구니 아이템 고유 ID';
COMMENT ON COLUMN CART_ITEM.MEMBER_ID IS '회원 ID';
COMMENT ON COLUMN CART_ITEM.ITEM_TYPE IS '아이템 타입 (HOUSE: 숙소, CAR: 차량)';
COMMENT ON COLUMN CART_ITEM.ITEM_ID IS '숙소 ID 또는 차량 ID';
COMMENT ON COLUMN CART_ITEM.START_DATE IS '예약 시작일';
COMMENT ON COLUMN CART_ITEM.END_DATE IS '예약 종료일';
COMMENT ON COLUMN CART_ITEM.QUANTITY IS '수량 (숙소: 인원수, 차량: 1)';
COMMENT ON COLUMN CART_ITEM.UNIT_PRICE IS '일일 요금';
COMMENT ON COLUMN CART_ITEM.TOTAL_PRICE IS '총 요금';
COMMENT ON COLUMN CART_ITEM.ITEM_NAME IS '아이템명 (숙소명 또는 차량명)';
COMMENT ON COLUMN CART_ITEM.ITEM_IMAGE IS '이미지 URL';
COMMENT ON COLUMN CART_ITEM.ITEM_TYPE_NAME IS '아이템 타입명 (숙소 타입 또는 차량 타입)';
COMMENT ON COLUMN CART_ITEM.PICKUP_LOCATION IS '차량 수령 장소 (차량인 경우)';
COMMENT ON COLUMN CART_ITEM.RETURN_LOCATION IS '차량 반납 장소 (차량인 경우)';
COMMENT ON COLUMN CART_ITEM.ROOM_TYPE IS '객실 타입 (숙소인 경우)';
COMMENT ON COLUMN CART_ITEM.CREATED_AT IS '생성일시';
COMMENT ON COLUMN CART_ITEM.UPDATED_AT IS '수정일시'; 