-- 기존 테이블 삭제
DROP TABLE TRAIN_ROUTE;
DROP TABLE TRAIN_STATION;
DROP TABLE TRAIN_KIND;
DROP TABLE TRAIN_CITY;

-- 테이블 생성
CREATE TABLE TRAIN_CITY(
  CITY_CODE NUMBER PRIMARY KEY,
  CITY_NAME VARCHAR2(20)
);

CREATE TABLE TRAIN_KIND(
  VEHICLE_KIND_ID VARCHAR2(20) PRIMARY KEY,
  VEHICLE_KIND_NM VARCHAR2(50),
  IS_ACTIVE NUMBER(1) DEFAULT 1,
  CREATED_AT DATE DEFAULT SYSDATE,
  UPDATED_AT DATE DEFAULT SYSDATE
);

CREATE TABLE TRAIN_STATION(
  NODE_ID VARCHAR2(20) PRIMARY KEY,
  NODE_NAME VARCHAR2(50),
  CITY_CODE NUMBER
);

-- 시퀀스 생성
CREATE SEQUENCE TRAIN_ROUTE_SEQ;

CREATE TABLE TRAIN_ROUTE(
  TRAIN_ROUTE_ID NUMBER PRIMARY KEY,
  TRAIN_NO NUMBER,
  DEP_PLACE_NAME VARCHAR2(50),
  ARR_PLACE_NAME VARCHAR2(50),
  DEP_PLAND_TIME TIMESTAMP,
  ARR_PLAND_TIME TIMESTAMP,
  TRAIN_GRADE_NAME VARCHAR2(30),
  ADULT_CHARGE NUMBER
); 