data-config:
  db-url: jdbc:oracle:thin:@211.238.142.200:1521:xe #211.238.142.200
  db-username: fteam02 #fteam02 #user01
  db-password: f1234 #f1234 #1234
  google-mail-url: dragonyxit@gmail.com
  google-mail-password: tepmacdqorgmlbfx
  rememberMe-key: hayden
  api:
    service-key: nqdefZ0rPUt2bdW%2F1Y%2FSRq%2Bb4knLjMYY1MQN7vktElEOlDQLAM3uvrs%2Fh2aos2ptIHeU%2FRqGH%2FhJaMPmgDax2Q%3D%3D
    tour:
      base-url: http://apis.data.go.kr/B551011/KorService2
    train:
      base-url: http://apis.data.go.kr/1613000/TrainInfoService
    express-bus:
      base-url: http://apis.data.go.kr/1613000/ExpBusInfoService
    kakao:
      base-url: https://dapi.kakao.com
      service-key: 83d842dabcdca653c2f46d1d81847c60
      search:
        base-url:
