dataconfig:
  db-url: jdbc:oracle:thin:@localhost:1521:xe #211.238.142.200
  db-username: user01 #fteam02
  db-password: 1234 #f1234
  google-mail-url: dragonyxit@gmail.com
  google-mail-password: tepmacdqorgmlbfx
  rememberme-key: hayden