--------------------------------------------------------
--  파일이 생성됨 - 화요일-7월-01-2025   
--------------------------------------------------------
--------------------------------------------------------
--  DDL for Sequence ADMIN_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ADMIN_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence API_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "API_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1521 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence API_SYNC_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "API_SYNC_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BUS_RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BUS_RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence BUS_ROUTE_INFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "BUS_ROUTE_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CAR_RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CAR_RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CAR_SELLER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CAR_SELLER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence CAR_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "CAR_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_CONTENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_CONTENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 5741 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_TAG_MAP_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_TAG_MAP_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence EVENT_TAG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "EVENT_TAG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence FAQ_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "FAQ_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence HOUSE_RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOUSE_RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence HOUSE_REVIEW_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOUSE_REVIEW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence HOUSE_SELLER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOUSE_SELLER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence HOUSE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "HOUSE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7981 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence INQUIRY_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "INQUIRY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence MEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "MEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 14 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence NOTICE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "NOTICE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence ROOM_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "ROOM_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SELLER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SELLER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence SPMEMBER_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "SPMEMBER_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TOUR_CONTENT_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOUR_CONTENT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 139701 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TOUR_PLACE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOUR_PLACE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TOUR_PLACE_TAG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOUR_PLACE_TAG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TOUR_TAG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TOUR_TAG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TRAIN_RESERVATION_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN_RESERVATION_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TRAIN_ROUTE_INFO_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN_ROUTE_INFO_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TRAIN_ROUTE_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRAIN_ROUTE_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 7981 CACHE 20 NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Sequence TRANSACTION_LOG_SEQ
--------------------------------------------------------

   CREATE SEQUENCE  "TRANSACTION_LOG_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 1 NOCACHE  NOORDER  NOCYCLE  NOKEEP  NOSCALE  GLOBAL ;
--------------------------------------------------------
--  DDL for Table ADMIN
--------------------------------------------------------

  CREATE TABLE "ADMIN" 
   (	"ADMIN_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "ADMIN"."ADMIN_ID" IS '관리자 ID';
   COMMENT ON COLUMN "ADMIN"."USERNAME" IS '사용자명 (로그인용)';
   COMMENT ON COLUMN "ADMIN"."PASSWORD" IS '비밀번호 (암호화)';
   COMMENT ON COLUMN "ADMIN"."NAME" IS '이름';
   COMMENT ON COLUMN "ADMIN"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "ADMIN"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "ADMIN"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "ADMIN"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "ADMIN"  IS '관리자 테이블';
--------------------------------------------------------
--  DDL for Table API_LOG
--------------------------------------------------------

  CREATE TABLE "API_LOG" 
   (	"LOG_ID" NUMBER, 
	"API_NAME" VARCHAR2(100 BYTE), 
	"REQUEST_URL" VARCHAR2(1000 BYTE), 
	"REQUEST_PARAMS" VARCHAR2(1000 BYTE), 
	"RESPONSE_CODE" VARCHAR2(50 BYTE), 
	"RESPONSE_MESSAGE" VARCHAR2(200 BYTE), 
	"RESPONSE_DATA" CLOB, 
	"ITEM_COUNT" NUMBER, 
	"IS_SUCCESS" NUMBER(1,0) DEFAULT 0, 
	"EXECUTION_TIME" NUMBER, 
	"REQUEST_TIME" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"RESPONSE_TIME" TIMESTAMP (6), 
	"ERROR_MESSAGE" VARCHAR2(4000 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("RESPONSE_DATA") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "API_LOG"."LOG_ID" IS '로그 ID (PK)';
   COMMENT ON COLUMN "API_LOG"."API_NAME" IS 'API 이름 또는 경로';
   COMMENT ON COLUMN "API_LOG"."REQUEST_URL" IS '요청 URL';
   COMMENT ON COLUMN "API_LOG"."REQUEST_PARAMS" IS '요청 파라미터 (JSON 형식)';
   COMMENT ON COLUMN "API_LOG"."RESPONSE_CODE" IS '응답 코드';
   COMMENT ON COLUMN "API_LOG"."RESPONSE_MESSAGE" IS '응답 메시지';
   COMMENT ON COLUMN "API_LOG"."RESPONSE_DATA" IS '응답 데이터 (일부 또는 요약)';
   COMMENT ON COLUMN "API_LOG"."ITEM_COUNT" IS '응답 항목 수';
   COMMENT ON COLUMN "API_LOG"."IS_SUCCESS" IS '성공 여부 (1=성공, 0=실패)';
   COMMENT ON COLUMN "API_LOG"."EXECUTION_TIME" IS '실행 시간 (ms)';
   COMMENT ON COLUMN "API_LOG"."REQUEST_TIME" IS '요청 시간';
   COMMENT ON COLUMN "API_LOG"."RESPONSE_TIME" IS '응답 시간';
   COMMENT ON COLUMN "API_LOG"."ERROR_MESSAGE" IS '오류 메시지 (있는 경우)';
   COMMENT ON TABLE "API_LOG"  IS 'API 호출 로그';
--------------------------------------------------------
--  DDL for Table AREA
--------------------------------------------------------

  CREATE TABLE "AREA" 
   (	"AREA_CODE" NUMBER, 
	"AREA_NAME" VARCHAR2(100 BYTE), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "AREA"."AREA_CODE" IS '지역코드';
   COMMENT ON COLUMN "AREA"."AREA_NAME" IS '지역명';
   COMMENT ON COLUMN "AREA"."IS_ACTIVE" IS '활성화 여부 (Y:활성, N:비활성)';
   COMMENT ON COLUMN "AREA"."CREATED_AT" IS '생성일시';
   COMMENT ON TABLE "AREA"  IS '지역코드 관리 테이블 (관광API용)';
--------------------------------------------------------
--  DDL for Table BUS_GRADE
--------------------------------------------------------

  CREATE TABLE "BUS_GRADE" 
   (	"GRADE_ID" VARCHAR2(3 BYTE), 
	"GRADE_NAME" VARCHAR2(20 BYTE), 
	"GRADE_TYPE" VARCHAR2(20 BYTE) DEFAULT 'SUBURBS', 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"API_LAST_SYNC" DATE DEFAULT SYSDATE, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "BUS_GRADE"."GRADE_ID" IS '버스 등급 ID';
   COMMENT ON COLUMN "BUS_GRADE"."GRADE_NAME" IS '버스 등급명';
   COMMENT ON COLUMN "BUS_GRADE"."GRADE_TYPE" IS '버스 타입 (SUBURBS:시외버스, EXPRESS:고속버스)';
   COMMENT ON COLUMN "BUS_GRADE"."IS_ACTIVE" IS '활성화 여부 (Y:활성, N:비활성)';
   COMMENT ON COLUMN "BUS_GRADE"."API_LAST_SYNC" IS 'API 마지막 동기화 시간';
   COMMENT ON COLUMN "BUS_GRADE"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "BUS_GRADE"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "BUS_GRADE"  IS '버스 등급 테이블';
--------------------------------------------------------
--  DDL for Table CAR_SELLER
--------------------------------------------------------

  CREATE TABLE "CAR_SELLER" 
   (	"CAR_SELLER_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"COMPANY_NAME" VARCHAR2(200 BYTE), 
	"BUSINESS_NUMBER" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "CAR_SELLER"."CAR_SELLER_ID" IS '렌터카 판매자 ID';
   COMMENT ON COLUMN "CAR_SELLER"."USERNAME" IS '사용자명 (로그인용)';
   COMMENT ON COLUMN "CAR_SELLER"."PASSWORD" IS '비밀번호 (암호화)';
   COMMENT ON COLUMN "CAR_SELLER"."COMPANY_NAME" IS '회사명';
   COMMENT ON COLUMN "CAR_SELLER"."BUSINESS_NUMBER" IS '사업자등록번호';
   COMMENT ON COLUMN "CAR_SELLER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "CAR_SELLER"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "CAR_SELLER"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "CAR_SELLER"."STATUS" IS '상태 (PENDING:대기, APPROVED:승인, REJECTED:거부, SUSPENDED:정지)';
   COMMENT ON COLUMN "CAR_SELLER"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "CAR_SELLER"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "CAR_SELLER"  IS '렌터카 판매자 테이블';
--------------------------------------------------------
--  DDL for Table EVENT_CONTENT
--------------------------------------------------------

  CREATE TABLE "EVENT_CONTENT" 
   (	"ID" NUMBER, 
	"CONTENTID" VARCHAR2(20 BYTE), 
	"CONTENTTYPEID" VARCHAR2(10 BYTE), 
	"TITLE" VARCHAR2(200 BYTE), 
	"ADDR1" VARCHAR2(200 BYTE), 
	"ADDR2" VARCHAR2(200 BYTE), 
	"ZIPCODE" VARCHAR2(10 BYTE), 
	"TEL" VARCHAR2(500 BYTE), 
	"CAT1" VARCHAR2(10 BYTE), 
	"CAT2" VARCHAR2(10 BYTE), 
	"CAT3" VARCHAR2(10 BYTE), 
	"AREACODE" VARCHAR2(10 BYTE), 
	"SIGUNGUCODE" VARCHAR2(10 BYTE), 
	"MAPX" VARCHAR2(30 BYTE), 
	"MAPY" VARCHAR2(30 BYTE), 
	"FIRSTIMAGE" VARCHAR2(500 BYTE), 
	"FIRSTIMAGE2" VARCHAR2(500 BYTE), 
	"EVENTSTARTDATE" VARCHAR2(20 BYTE), 
	"EVENTENDDATE" VARCHAR2(20 BYTE), 
	"CREATEDTIME" VARCHAR2(20 BYTE), 
	"MODIFIEDTIME" VARCHAR2(20 BYTE), 
	"CPYRHTDIVCD" VARCHAR2(10 BYTE), 
	"MLEVEL" VARCHAR2(10 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSTIMESTAMP
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table EXPRESS_BUS_CITY
--------------------------------------------------------

  CREATE TABLE "EXPRESS_BUS_CITY" 
   (	"CITY_CODE" NUMBER, 
	"CITY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

   COMMENT ON TABLE "EXPRESS_BUS_CITY"  IS 'API에서 주길래 만들긴했는데 어디에쓰는진 몰겠음';
--------------------------------------------------------
--  DDL for Table EXPRESS_BUS_GRADE
--------------------------------------------------------

  CREATE TABLE "EXPRESS_BUS_GRADE" 
   (	"GRADE_ID" NUMBER, 
	"GRADE_NM" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table EXPRESS_BUS_TERMINAL
--------------------------------------------------------

  CREATE TABLE "EXPRESS_BUS_TERMINAL" 
   (	"TERMINAL_ID" VARCHAR2(20 BYTE), 
	"TERMINAL_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table FAQ
--------------------------------------------------------

  CREATE TABLE "FAQ" 
   (	"FAQ_ID" NUMBER, 
	"CATEGORY" VARCHAR2(50 BYTE) DEFAULT 'GENERAL', 
	"QUESTION" VARCHAR2(300 BYTE), 
	"ANSWER" CLOB, 
	"ORDER_NUM" NUMBER DEFAULT 1, 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("ANSWER") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "FAQ"."FAQ_ID" IS 'FAQ ID';
   COMMENT ON COLUMN "FAQ"."CATEGORY" IS '카테고리';
   COMMENT ON COLUMN "FAQ"."QUESTION" IS '질문';
   COMMENT ON COLUMN "FAQ"."ANSWER" IS '답변';
   COMMENT ON COLUMN "FAQ"."ORDER_NUM" IS '정렬순서';
   COMMENT ON COLUMN "FAQ"."IS_ACTIVE" IS '활성화 여부 (Y:활성, N:비활성)';
   COMMENT ON COLUMN "FAQ"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "FAQ"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "FAQ"  IS 'FAQ 테이블';
--------------------------------------------------------
--  DDL for Table HOUSE
--------------------------------------------------------

  CREATE TABLE "HOUSE" 
   (	"ID" NUMBER, 
	"ADDR1" VARCHAR2(500 BYTE), 
	"ADDR2" VARCHAR2(500 BYTE), 
	"AREA_CODE" NUMBER, 
	"CAT1" VARCHAR2(10 BYTE), 
	"CAT2" VARCHAR2(10 BYTE), 
	"CAT3" VARCHAR2(10 BYTE), 
	"CONTENT_ID" NUMBER, 
	"CONTENT_TYPE_ID" NUMBER, 
	"CREATED_AT" TIMESTAMP (6), 
	"UPDATED_AT" TIMESTAMP (6), 
	"FIRST_IMAGE" VARCHAR2(1000 BYTE), 
	"FIRST_IMAGE2" VARCHAR2(1000 BYTE), 
	"CPYRHT_DIV_CD" VARCHAR2(20 BYTE), 
	"MAP_X" NUMBER(15,8), 
	"MAP_Y" NUMBER(15,8), 
	"SIGUNGU_CODE" NUMBER, 
	"TEL" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(500 BYTE), 
	"ZIPCODE" NUMBER, 
	"MLEVEL" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table HOUSE_SELLER
--------------------------------------------------------

  CREATE TABLE "HOUSE_SELLER" 
   (	"SELLER_ID" NUMBER, 
	"USERNAME" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"COMPANY_NAME" VARCHAR2(200 BYTE), 
	"BUSINESS_NUMBER" VARCHAR2(50 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'PENDING', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "HOUSE_SELLER"."SELLER_ID" IS '판매자 ID';
   COMMENT ON COLUMN "HOUSE_SELLER"."USERNAME" IS '사용자명 (로그인용)';
   COMMENT ON COLUMN "HOUSE_SELLER"."PASSWORD" IS '비밀번호 (암호화)';
   COMMENT ON COLUMN "HOUSE_SELLER"."COMPANY_NAME" IS '회사명';
   COMMENT ON COLUMN "HOUSE_SELLER"."BUSINESS_NUMBER" IS '사업자등록번호';
   COMMENT ON COLUMN "HOUSE_SELLER"."EMAIL" IS '이메일';
   COMMENT ON COLUMN "HOUSE_SELLER"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "HOUSE_SELLER"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "HOUSE_SELLER"."STATUS" IS '상태 (PENDING:대기, APPROVED:승인, REJECTED:거부, SUSPENDED:정지)';
   COMMENT ON COLUMN "HOUSE_SELLER"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "HOUSE_SELLER"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "HOUSE_SELLER"  IS '숙박업체 판매자 테이블';
--------------------------------------------------------
--  DDL for Table MEMBER
--------------------------------------------------------

  CREATE TABLE "MEMBER" 
   (	"MEMBER_ID" NUMBER, 
	"ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(300 BYTE), 
	"NAME" VARCHAR2(20 BYTE), 
	"EMAIL" VARCHAR2(200 BYTE), 
	"PHONE" VARCHAR2(50 BYTE), 
	"ADDRESS" VARCHAR2(200 BYTE), 
	"ADDRESS_DETAIL" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'ACTIVE', 
	"ROLE" VARCHAR2(20 BYTE) DEFAULT 'MEMBER', 
	"CREATED_AT" DATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table NOTICE
--------------------------------------------------------

  CREATE TABLE "NOTICE" 
   (	"NOTICE_ID" NUMBER, 
	"ADMIN_ID" NUMBER, 
	"TITLE" VARCHAR2(200 BYTE), 
	"CONTENT" CLOB, 
	"IS_IMPORTANT" CHAR(1 BYTE) DEFAULT 'N', 
	"VIEW_COUNT" NUMBER DEFAULT 0, 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("CONTENT") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "NOTICE"."NOTICE_ID" IS '공지사항 ID';
   COMMENT ON COLUMN "NOTICE"."ADMIN_ID" IS '작성자 (관리자 ID)';
   COMMENT ON COLUMN "NOTICE"."TITLE" IS '제목';
   COMMENT ON COLUMN "NOTICE"."CONTENT" IS '내용';
   COMMENT ON COLUMN "NOTICE"."IS_IMPORTANT" IS '중요공지 여부 (Y:중요, N:일반)';
   COMMENT ON COLUMN "NOTICE"."VIEW_COUNT" IS '조회수';
   COMMENT ON COLUMN "NOTICE"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "NOTICE"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "NOTICE"  IS '공지사항 테이블';
--------------------------------------------------------
--  DDL for Table PERSISTENT_LOGINS
--------------------------------------------------------

  CREATE TABLE "PERSISTENT_LOGINS" 
   (	"SERIES" VARCHAR2(64 BYTE), 
	"USERNAME" VARCHAR2(64 BYTE), 
	"TOKEN" VARCHAR2(64 BYTE), 
	"LAST_USED" TIMESTAMP (6)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SELLER
--------------------------------------------------------

  CREATE TABLE "SELLER" 
   (	"SELLER_ID" NUMBER(19,0), 
	"LOGIN_ID" VARCHAR2(50 BYTE), 
	"PASSWORD" VARCHAR2(100 BYTE), 
	"NAME" VARCHAR2(100 BYTE), 
	"EMAIL" VARCHAR2(100 BYTE), 
	"LICENSE" VARCHAR2(50 BYTE), 
	"SELLER_TYPE" VARCHAR2(50 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'ACTIVE', 
	"ADDRESS" VARCHAR2(255 BYTE), 
	"ADDRESS_DETAIL" VARCHAR2(255 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"SECONDARY_PHONE" VARCHAR2(20 BYTE), 
	"ROLE" VARCHAR2(50 BYTE) DEFAULT 'SELLER', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SERVICE_CATEGORY
--------------------------------------------------------

  CREATE TABLE "SERVICE_CATEGORY" 
   (	"CATEGORY_CODE" VARCHAR2(20 BYTE), 
	"CATEGORY_NAME" VARCHAR2(100 BYTE), 
	"PARENT_CODE" VARCHAR2(20 BYTE), 
	"CODE_LEVEL" NUMBER(1,0), 
	"CONTENT_TYPE_ID" VARCHAR2(10 BYTE), 
	"IS_ACTIVE" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "SERVICE_CATEGORY"."CATEGORY_CODE" IS '분류코드';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."CATEGORY_NAME" IS '분류명';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."PARENT_CODE" IS '상위 분류코드';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."CODE_LEVEL" IS '분류 레벨 (1:대분류, 2:중분류, 3:소분류)';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."CONTENT_TYPE_ID" IS '콘텐츠 타입 ID';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."IS_ACTIVE" IS '활성화 여부 (Y:활성, N:비활성)';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "SERVICE_CATEGORY"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "SERVICE_CATEGORY"  IS '분류코드 관리 테이블 (관광API용)';
--------------------------------------------------------
--  DDL for Table SIGUNGU
--------------------------------------------------------

  CREATE TABLE "SIGUNGU" 
   (	"AREA_CODE" NUMBER, 
	"SIGUNGU_CODE" NUMBER, 
	"SIGUNGU_NAME" VARCHAR2(20 BYTE), 
	"IS_ACTIVE" NUMBER DEFAULT 1
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table SPMEMBER
--------------------------------------------------------

  CREATE TABLE "SPMEMBER" 
   (	"MEM_NUM" NUMBER, 
	"ID" VARCHAR2(16 BYTE), 
	"NICK_NAME" VARCHAR2(30 BYTE), 
	"AUTHORITY" VARCHAR2(30 BYTE) DEFAULT 'ROLE_USER'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table SPMEMBER_DETAIL
--------------------------------------------------------

  CREATE TABLE "SPMEMBER_DETAIL" 
   (	"MEM_NUM" NUMBER, 
	"NAME" VARCHAR2(30 BYTE), 
	"PASSWD" VARCHAR2(60 BYTE), 
	"PHONE" VARCHAR2(15 BYTE), 
	"EMAIL" VARCHAR2(50 BYTE), 
	"ZIPCODE" VARCHAR2(5 BYTE), 
	"ADDRESS1" VARCHAR2(120 BYTE), 
	"ADDRESS2" VARCHAR2(90 BYTE), 
	"PHOTO" BLOB, 
	"PHOTO_NAME" VARCHAR2(100 BYTE), 
	"REG_DATE" DATE DEFAULT sysdate, 
	"MODIFY_DATE" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" 
 LOB ("PHOTO") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW 4000 CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES 
  STORAGE(INITIAL 262144 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;
--------------------------------------------------------
--  DDL for Table TOUR_CATEGORY_CODE
--------------------------------------------------------

  CREATE TABLE "TOUR_CATEGORY_CODE" 
   (	"TOUR_CONTENT_ID" NUMBER, 
	"TOUR_CONTENT_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TOUR_CONTENT
--------------------------------------------------------

  CREATE TABLE "TOUR_CONTENT" 
   (	"ID" NUMBER, 
	"ADDR1" VARCHAR2(500 BYTE), 
	"ADDR2" VARCHAR2(500 BYTE), 
	"AREA_CODE" NUMBER, 
	"CAT1" VARCHAR2(10 BYTE), 
	"CAT2" VARCHAR2(20 BYTE), 
	"CAT3" VARCHAR2(20 BYTE), 
	"CONTENT_ID" NUMBER, 
	"CONTENT_TYPE_ID" NUMBER, 
	"FIRST_IMAGE" VARCHAR2(1000 BYTE), 
	"FIRST_IMAGE2" VARCHAR2(1000 BYTE), 
	"CPYRHT_DIV_CD" VARCHAR2(20 BYTE), 
	"MAP_X" NUMBER(15,8), 
	"MAP_Y" NUMBER(15,8), 
	"MLEVEL" NUMBER, 
	"SIGUNGU_CODE" NUMBER, 
	"TEL" VARCHAR2(100 BYTE), 
	"TITLE" VARCHAR2(500 BYTE), 
	"ZIPCODE" VARCHAR2(10 BYTE), 
	"CREATED_AT" TIMESTAMP (6) DEFAULT NULL, 
	"UPDATED_AT" TIMESTAMP (6) DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TOUR_CONTENT"."ID" IS 'DB상의 고유 식별 ID';
   COMMENT ON COLUMN "TOUR_CONTENT"."ADDR1" IS '주소';
   COMMENT ON COLUMN "TOUR_CONTENT"."ADDR2" IS '상세주소';
   COMMENT ON COLUMN "TOUR_CONTENT"."AREA_CODE" IS '지역코드';
   COMMENT ON COLUMN "TOUR_CONTENT"."CAT1" IS '서비스 대분류
';
   COMMENT ON COLUMN "TOUR_CONTENT"."CAT2" IS '서비스 중분류';
   COMMENT ON COLUMN "TOUR_CONTENT"."CAT3" IS '서비스 소분류
';
   COMMENT ON COLUMN "TOUR_CONTENT"."CONTENT_ID" IS '콘텐츠 고유ID
';
   COMMENT ON COLUMN "TOUR_CONTENT"."CONTENT_TYPE_ID" IS '컨텐츠 카테고 리 ID
';
   COMMENT ON COLUMN "TOUR_CONTENT"."FIRST_IMAGE" IS '큰 이미지
';
   COMMENT ON COLUMN "TOUR_CONTENT"."FIRST_IMAGE2" IS '썸네일 이미지

';
   COMMENT ON COLUMN "TOUR_CONTENT"."CPYRHT_DIV_CD" IS '저작권 관련
';
   COMMENT ON COLUMN "TOUR_CONTENT"."MAP_X" IS '지도상 X좌표
';
   COMMENT ON COLUMN "TOUR_CONTENT"."MAP_Y" IS '지도상 Y좌표';
   COMMENT ON COLUMN "TOUR_CONTENT"."MLEVEL" IS '지도레벨';
   COMMENT ON COLUMN "TOUR_CONTENT"."SIGUNGU_CODE" IS '시군구코드';
   COMMENT ON COLUMN "TOUR_CONTENT"."TEL" IS '전화번호';
   COMMENT ON COLUMN "TOUR_CONTENT"."TITLE" IS '이름';
   COMMENT ON COLUMN "TOUR_CONTENT"."ZIPCODE" IS '우편번호';
--------------------------------------------------------
--  DDL for Table TOUR_PLACE
--------------------------------------------------------

  CREATE TABLE "TOUR_PLACE" 
   (	"TOUR_ID" NUMBER, 
	"CONTENT_ID" VARCHAR2(20 BYTE), 
	"NAME" VARCHAR2(200 BYTE), 
	"DESCRIPTION" CLOB, 
	"LOCATION" VARCHAR2(200 BYTE), 
	"ADDRESS" VARCHAR2(300 BYTE), 
	"LATITUDE" NUMBER(10,8), 
	"LONGITUDE" NUMBER(11,8), 
	"OPEN_HOURS" VARCHAR2(100 BYTE), 
	"PHONE" VARCHAR2(20 BYTE), 
	"WEBSITE" VARCHAR2(200 BYTE), 
	"ENTRY_FEE" NUMBER DEFAULT 0, 
	"IS_PUBLIC" CHAR(1 BYTE) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" 
 LOB ("DESCRIPTION") STORE AS BASICFILE (
  TABLESPACE "SYSTEM" ENABLE STORAGE IN ROW 4000 CHUNK 8192 RETENTION 
  NOCACHE LOGGING 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)) ;

   COMMENT ON COLUMN "TOUR_PLACE"."TOUR_ID" IS '관광지 ID';
   COMMENT ON COLUMN "TOUR_PLACE"."CONTENT_ID" IS '관광API 콘텐츠 ID';
   COMMENT ON COLUMN "TOUR_PLACE"."NAME" IS '관광지명';
   COMMENT ON COLUMN "TOUR_PLACE"."DESCRIPTION" IS '설명';
   COMMENT ON COLUMN "TOUR_PLACE"."LOCATION" IS '위치';
   COMMENT ON COLUMN "TOUR_PLACE"."ADDRESS" IS '주소';
   COMMENT ON COLUMN "TOUR_PLACE"."LATITUDE" IS '위도';
   COMMENT ON COLUMN "TOUR_PLACE"."LONGITUDE" IS '경도';
   COMMENT ON COLUMN "TOUR_PLACE"."OPEN_HOURS" IS '운영시간';
   COMMENT ON COLUMN "TOUR_PLACE"."PHONE" IS '전화번호';
   COMMENT ON COLUMN "TOUR_PLACE"."WEBSITE" IS '웹사이트';
   COMMENT ON COLUMN "TOUR_PLACE"."ENTRY_FEE" IS '입장료';
   COMMENT ON COLUMN "TOUR_PLACE"."IS_PUBLIC" IS '공개 여부 (Y:공개, N:비공개)';
   COMMENT ON COLUMN "TOUR_PLACE"."CREATED_AT" IS '생성일시';
   COMMENT ON COLUMN "TOUR_PLACE"."UPDATED_AT" IS '수정일시';
   COMMENT ON TABLE "TOUR_PLACE"  IS '관광지 테이블';
--------------------------------------------------------
--  DDL for Table TOUR_TAG
--------------------------------------------------------

  CREATE TABLE "TOUR_TAG" 
   (	"TAG_ID" NUMBER, 
	"NAME" VARCHAR2(100 BYTE), 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"CREATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TOUR_TAG"."TAG_ID" IS '태그 ID';
   COMMENT ON COLUMN "TOUR_TAG"."NAME" IS '태그명';
   COMMENT ON COLUMN "TOUR_TAG"."DESCRIPTION" IS '태그 설명';
   COMMENT ON COLUMN "TOUR_TAG"."CREATED_AT" IS '생성일시';
   COMMENT ON TABLE "TOUR_TAG"  IS '관광지 태그 테이블';
--------------------------------------------------------
--  DDL for Table TRAIN_CITY
--------------------------------------------------------

  CREATE TABLE "TRAIN_CITY" 
   (	"CITY_CODE" NUMBER, 
	"CITY_NAME" VARCHAR2(20 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Table TRAIN_HUB_STATION
--------------------------------------------------------

  CREATE TABLE "TRAIN_HUB_STATION" 
   (	"NODE_ID" VARCHAR2(20 BYTE), 
	"NODE_NAME" VARCHAR2(20 BYTE), 
	"IS_ACTIVE" VARCHAR2(5 BYTE) DEFAULT 'Y', 
	"CITY_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAIN_KIND
--------------------------------------------------------

  CREATE TABLE "TRAIN_KIND" 
   (	"VEHICLE_KIND_ID" VARCHAR2(20 BYTE), 
	"VEHICLE_KIND_NM" VARCHAR2(50 BYTE), 
	"IS_ACTIVE" VARCHAR2(5 BYTE) DEFAULT 'Y', 
	"CREATED_AT" DATE DEFAULT SYSDATE, 
	"UPDATED_AT" DATE DEFAULT SYSDATE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAIN_ROUTE
--------------------------------------------------------

  CREATE TABLE "TRAIN_ROUTE" 
   (	"TRAIN_ROUTE_ID" NUMBER, 
	"ADULT_CHARGE" NUMBER, 
	"ARR_PLACE_NAME" VARCHAR2(100 BYTE), 
	"DEP_PLACE_NAME" VARCHAR2(100 BYTE), 
	"ARR_PLAND_TIME" TIMESTAMP (6), 
	"DEP_PLAND_TIME" TIMESTAMP (6), 
	"TRAIN_GRADE_NAME" VARCHAR2(100 BYTE), 
	"TRAIN_NO" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRAIN_STATION
--------------------------------------------------------

  CREATE TABLE "TRAIN_STATION" 
   (	"NODE_ID" VARCHAR2(30 BYTE), 
	"NODE_NAME" VARCHAR2(30 BYTE), 
	"IS_ACTIVE" VARCHAR2(5 BYTE) DEFAULT 'Y', 
	"CITY_CODE" NUMBER
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Table TRANSACTION_LOG
--------------------------------------------------------

  CREATE TABLE "TRANSACTION_LOG" 
   (	"TRANSACTION_LOG_ID" NUMBER, 
	"USER_ID" NUMBER, 
	"SELLER_ID" NUMBER, 
	"CAR_SELLER_ID" NUMBER, 
	"TRANSACTION_TYPE" VARCHAR2(50 BYTE), 
	"AMOUNT" NUMBER, 
	"TRANSACTION_DATE" DATE DEFAULT SYSDATE, 
	"DESCRIPTION" VARCHAR2(200 BYTE), 
	"STATUS" VARCHAR2(20 BYTE) DEFAULT 'COMPLETED'
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;

   COMMENT ON COLUMN "TRANSACTION_LOG"."TRANSACTION_LOG_ID" IS '거래 로그 ID';
   COMMENT ON COLUMN "TRANSACTION_LOG"."USER_ID" IS '고객 ID';
   COMMENT ON COLUMN "TRANSACTION_LOG"."SELLER_ID" IS '숙박업체 판매자 ID';
   COMMENT ON COLUMN "TRANSACTION_LOG"."CAR_SELLER_ID" IS '렌터카 판매자 ID';
   COMMENT ON COLUMN "TRANSACTION_LOG"."TRANSACTION_TYPE" IS '거래 유형';
   COMMENT ON COLUMN "TRANSACTION_LOG"."AMOUNT" IS '거래 금액';
   COMMENT ON COLUMN "TRANSACTION_LOG"."TRANSACTION_DATE" IS '거래일시';
   COMMENT ON COLUMN "TRANSACTION_LOG"."DESCRIPTION" IS '거래 설명';
   COMMENT ON COLUMN "TRANSACTION_LOG"."STATUS" IS '거래상태 (PENDING:대기, COMPLETED:완료, FAILED:실패, CANCELLED:취소)';
   COMMENT ON TABLE "TRANSACTION_LOG"  IS '거래 로그 테이블';
--------------------------------------------------------
--  DDL for Index UQ_SELLER_EMAIL
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_SELLER_EMAIL" ON "SELLER" ("EMAIL") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index UQ_SELLER_LOGIN_ID
--------------------------------------------------------

  CREATE UNIQUE INDEX "UQ_SELLER_LOGIN_ID" ON "SELLER" ("LOGIN_ID") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index PK_SIGUNGU_CODE
--------------------------------------------------------

  CREATE UNIQUE INDEX "PK_SIGUNGU_CODE" ON "SIGUNGU" ("AREA_CODE", "SIGUNGU_CODE") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM" ;
--------------------------------------------------------
--  DDL for Index SPMEMBER_DETAIL_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPMEMBER_DETAIL_PK" ON "SPMEMBER_DETAIL" ("MEM_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  DDL for Index SPMEMBER_PK
--------------------------------------------------------

  CREATE UNIQUE INDEX "SPMEMBER_PK" ON "SPMEMBER" ("MEM_NUM") 
  PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
--------------------------------------------------------
--  Constraints for Table PERSISTENT_LOGINS
--------------------------------------------------------

  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("USERNAME" NOT NULL ENABLE);
  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("TOKEN" NOT NULL ENABLE);
  ALTER TABLE "PERSISTENT_LOGINS" MODIFY ("LAST_USED" NOT NULL ENABLE);
  ALTER TABLE "PERSISTENT_LOGINS" ADD PRIMARY KEY ("SERIES")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAIN_STATION
--------------------------------------------------------

  ALTER TABLE "TRAIN_STATION" ADD PRIMARY KEY ("NODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOUSE_SELLER
--------------------------------------------------------

  ALTER TABLE "HOUSE_SELLER" ADD CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')) ENABLE;
  ALTER TABLE "HOUSE_SELLER" ADD UNIQUE ("BUSINESS_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOUSE_SELLER" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOUSE_SELLER" ADD PRIMARY KEY ("SELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "HOUSE_SELLER" ADD CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')) ENABLE;
  ALTER TABLE "HOUSE_SELLER" MODIFY ("BUSINESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "HOUSE_SELLER" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "HOUSE_SELLER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "HOUSE_SELLER" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOUR_TAG
--------------------------------------------------------

  ALTER TABLE "TOUR_TAG" ADD UNIQUE ("NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOUR_TAG" ADD PRIMARY KEY ("TAG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOUR_TAG" MODIFY ("NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table SPMEMBER
--------------------------------------------------------

  ALTER TABLE "SPMEMBER" MODIFY ("MEM_NUM" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER" MODIFY ("AUTHORITY" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER" ADD CONSTRAINT "SPMEMBER_PK" PRIMARY KEY ("MEM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SPMEMBER" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SPMEMBER" ADD UNIQUE ("NICK_NAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAIN_HUB_STATION
--------------------------------------------------------

  ALTER TABLE "TRAIN_HUB_STATION" ADD PRIMARY KEY ("NODE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "NOTICE" ADD CHECK (IS_IMPORTANT IN ('Y','N')) ENABLE;
  ALTER TABLE "NOTICE" ADD PRIMARY KEY ("NOTICE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "NOTICE" ADD CHECK (IS_IMPORTANT IN ('Y','N')) ENABLE;
  ALTER TABLE "NOTICE" MODIFY ("TITLE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table CAR_SELLER
--------------------------------------------------------

  ALTER TABLE "CAR_SELLER" ADD CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')) ENABLE;
  ALTER TABLE "CAR_SELLER" ADD UNIQUE ("BUSINESS_NUMBER")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAR_SELLER" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAR_SELLER" ADD PRIMARY KEY ("CAR_SELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "CAR_SELLER" ADD CHECK (STATUS IN ('PENDING', 'APPROVED', 'REJECTED', 'SUSPENDED')) ENABLE;
  ALTER TABLE "CAR_SELLER" MODIFY ("BUSINESS_NUMBER" NOT NULL ENABLE);
  ALTER TABLE "CAR_SELLER" MODIFY ("COMPANY_NAME" NOT NULL ENABLE);
  ALTER TABLE "CAR_SELLER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "CAR_SELLER" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAIN_ROUTE
--------------------------------------------------------

  ALTER TABLE "TRAIN_ROUTE" ADD PRIMARY KEY ("TRAIN_ROUTE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table BUS_GRADE
--------------------------------------------------------

  ALTER TABLE "BUS_GRADE" ADD CHECK (GRADE_TYPE IN ('SUBURBS', 'EXPRESS')) ENABLE;
  ALTER TABLE "BUS_GRADE" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "BUS_GRADE" ADD PRIMARY KEY ("GRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "BUS_GRADE" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "BUS_GRADE" ADD CHECK (GRADE_TYPE IN ('SUBURBS', 'EXPRESS')) ENABLE;
  ALTER TABLE "BUS_GRADE" MODIFY ("GRADE_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EVENT_CONTENT
--------------------------------------------------------

  ALTER TABLE "EVENT_CONTENT" ADD UNIQUE ("CONTENTID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "EVENT_CONTENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table ADMIN
--------------------------------------------------------

  ALTER TABLE "ADMIN" ADD UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN" ADD UNIQUE ("USERNAME")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN" ADD PRIMARY KEY ("ADMIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "ADMIN" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "ADMIN" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "ADMIN" MODIFY ("USERNAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXPRESS_BUS_TERMINAL
--------------------------------------------------------

  ALTER TABLE "EXPRESS_BUS_TERMINAL" ADD PRIMARY KEY ("TERMINAL_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SELLER
--------------------------------------------------------

  ALTER TABLE "SELLER" MODIFY ("LOGIN_ID" NOT NULL ENABLE);
  ALTER TABLE "SELLER" MODIFY ("PASSWORD" NOT NULL ENABLE);
  ALTER TABLE "SELLER" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SELLER" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SELLER" ADD PRIMARY KEY ("SELLER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SELLER" ADD CONSTRAINT "UQ_SELLER_LOGIN_ID" UNIQUE ("LOGIN_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SELLER" ADD CONSTRAINT "UQ_SELLER_EMAIL" UNIQUE ("EMAIL")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "SELLER" MODIFY ("SELLER_TYPE" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TRAIN_KIND
--------------------------------------------------------

  ALTER TABLE "TRAIN_KIND" ADD PRIMARY KEY ("VEHICLE_KIND_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table API_LOG
--------------------------------------------------------

  ALTER TABLE "API_LOG" ADD PRIMARY KEY ("LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "API_LOG" MODIFY ("REQUEST_URL" NOT NULL ENABLE);
  ALTER TABLE "API_LOG" MODIFY ("API_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table AREA
--------------------------------------------------------

  ALTER TABLE "AREA" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "AREA" ADD PRIMARY KEY ("AREA_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "AREA" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "AREA" MODIFY ("AREA_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table EXPRESS_BUS_CITY
--------------------------------------------------------

  ALTER TABLE "EXPRESS_BUS_CITY" ADD PRIMARY KEY ("CITY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table HOUSE
--------------------------------------------------------

  ALTER TABLE "HOUSE" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SERVICE_CATEGORY
--------------------------------------------------------

  ALTER TABLE "SERVICE_CATEGORY" ADD CHECK (CODE_LEVEL IN (1,2,3)) ENABLE;
  ALTER TABLE "SERVICE_CATEGORY" ADD PRIMARY KEY ("CATEGORY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "SERVICE_CATEGORY" MODIFY ("CATEGORY_NAME" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table TOUR_PLACE
--------------------------------------------------------

  ALTER TABLE "TOUR_PLACE" ADD PRIMARY KEY ("TOUR_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOUR_PLACE" ADD CHECK (IS_PUBLIC IN ('Y','N')) ENABLE;
  ALTER TABLE "TOUR_PLACE" ADD CHECK (ENTRY_FEE >= 0) ENABLE;
  ALTER TABLE "TOUR_PLACE" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "TOUR_PLACE" ADD CHECK (ENTRY_FEE >= 0) ENABLE;
  ALTER TABLE "TOUR_PLACE" ADD CHECK (IS_PUBLIC IN ('Y','N')) ENABLE;
--------------------------------------------------------
--  Constraints for Table SPMEMBER_DETAIL
--------------------------------------------------------

  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("MEM_NUM" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("NAME" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("PASSWD" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("PHONE" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("EMAIL" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("ZIPCODE" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("ADDRESS1" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("ADDRESS2" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" MODIFY ("REG_DATE" NOT NULL ENABLE);
  ALTER TABLE "SPMEMBER_DETAIL" ADD CONSTRAINT "SPMEMBER_DETAIL_PK" PRIMARY KEY ("MEM_NUM")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRANSACTION_LOG
--------------------------------------------------------

  ALTER TABLE "TRANSACTION_LOG" ADD CHECK (AMOUNT >= 0) ENABLE;
  ALTER TABLE "TRANSACTION_LOG" ADD PRIMARY KEY ("TRANSACTION_LOG_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TRANSACTION_LOG" ADD CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')) ENABLE;
  ALTER TABLE "TRANSACTION_LOG" ADD CHECK (AMOUNT >= 0) ENABLE;
  ALTER TABLE "TRANSACTION_LOG" MODIFY ("AMOUNT" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTION_LOG" MODIFY ("TRANSACTION_TYPE" NOT NULL ENABLE);
  ALTER TABLE "TRANSACTION_LOG" ADD CHECK (STATUS IN ('PENDING', 'COMPLETED', 'FAILED', 'CANCELLED')) ENABLE;
--------------------------------------------------------
--  Constraints for Table EXPRESS_BUS_GRADE
--------------------------------------------------------

  ALTER TABLE "EXPRESS_BUS_GRADE" ADD PRIMARY KEY ("GRADE_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table FAQ
--------------------------------------------------------

  ALTER TABLE "FAQ" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "FAQ" ADD PRIMARY KEY ("FAQ_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "FAQ" ADD CHECK (IS_ACTIVE IN ('Y','N')) ENABLE;
  ALTER TABLE "FAQ" MODIFY ("QUESTION" NOT NULL ENABLE);
--------------------------------------------------------
--  Constraints for Table MEMBER
--------------------------------------------------------

  ALTER TABLE "MEMBER" MODIFY ("ID" NOT NULL ENABLE);
  ALTER TABLE "MEMBER" ADD PRIMARY KEY ("MEMBER_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
  ALTER TABLE "MEMBER" ADD UNIQUE ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE;
--------------------------------------------------------
--  Constraints for Table SIGUNGU
--------------------------------------------------------

  ALTER TABLE "SIGUNGU" ADD CONSTRAINT "PK_SIGUNGU_CODE" PRIMARY KEY ("AREA_CODE", "SIGUNGU_CODE")
  USING INDEX "PK_SIGUNGU_CODE"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TRAIN_CITY
--------------------------------------------------------

  ALTER TABLE "TRAIN_CITY" ADD PRIMARY KEY ("CITY_CODE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TOUR_CATEGORY_CODE
--------------------------------------------------------

  ALTER TABLE "TOUR_CATEGORY_CODE" ADD PRIMARY KEY ("TOUR_CONTENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Constraints for Table TOUR_CONTENT
--------------------------------------------------------

  ALTER TABLE "TOUR_CONTENT" ADD UNIQUE ("CONTENT_ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
  ALTER TABLE "TOUR_CONTENT" ADD PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "SYSTEM"  ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table HOUSE
--------------------------------------------------------

  ALTER TABLE "HOUSE" ADD CONSTRAINT "FK_HOUSE_AREA_CODE" FOREIGN KEY ("AREA_CODE")
	  REFERENCES "AREA" ("AREA_CODE") ENABLE;
  ALTER TABLE "HOUSE" ADD CONSTRAINT "FK_HOUSE_CAT1" FOREIGN KEY ("CAT1")
	  REFERENCES "SERVICE_CATEGORY" ("CATEGORY_CODE") ENABLE;
  ALTER TABLE "HOUSE" ADD CONSTRAINT "FK_HOUSE_CAT2" FOREIGN KEY ("CAT2")
	  REFERENCES "SERVICE_CATEGORY" ("CATEGORY_CODE") ENABLE;
  ALTER TABLE "HOUSE" ADD CONSTRAINT "FK_HOUSE_CAT3" FOREIGN KEY ("CAT3")
	  REFERENCES "SERVICE_CATEGORY" ("CATEGORY_CODE") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table NOTICE
--------------------------------------------------------

  ALTER TABLE "NOTICE" ADD CONSTRAINT "FK_NOTICE_ADMIN" FOREIGN KEY ("ADMIN_ID")
	  REFERENCES "ADMIN" ("ADMIN_ID") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table SPMEMBER_DETAIL
--------------------------------------------------------

  ALTER TABLE "SPMEMBER_DETAIL" ADD CONSTRAINT "SPMEMBER_DETAIL_FK" FOREIGN KEY ("MEM_NUM")
	  REFERENCES "SPMEMBER" ("MEM_NUM") ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRAIN_STATION
--------------------------------------------------------

  ALTER TABLE "TRAIN_STATION" ADD CONSTRAINT "FK_TRAIN_STATION" FOREIGN KEY ("CITY_CODE")
	  REFERENCES "TRAIN_CITY" ("CITY_CODE") ON DELETE SET NULL ENABLE;
--------------------------------------------------------
--  Ref Constraints for Table TRANSACTION_LOG
--------------------------------------------------------

  ALTER TABLE "TRANSACTION_LOG" ADD CONSTRAINT "FK_TRANSACTION_CAR_SELLER" FOREIGN KEY ("CAR_SELLER_ID")
	  REFERENCES "CAR_SELLER" ("CAR_SELLER_ID") ON DELETE SET NULL ENABLE;
  ALTER TABLE "TRANSACTION_LOG" ADD CONSTRAINT "FK_TRANSACTION_SELLER" FOREIGN KEY ("SELLER_ID")
	  REFERENCES "HOUSE_SELLER" ("SELLER_ID") ON DELETE SET NULL ENABLE;


-- HardCoding Content_Type_COde
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (12, '관광지');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (14, '문화시설');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (15, '축제공연행사');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (25, '여행코스');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (28, '레포츠');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (32, '숙박');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (38, '쇼핑');
INSERT INTO TOUR_CONTENT_CODE (CONTENT_TYPE_CODE, CONTENT_TYPE_NAME) VALUES (39, '음식점');